const routes = {
    '/': { slug: 'home', source: 'wordpress' },
    '/homes': { slug: 'homes', source: 'wordpress' },
    '/epc': { slug: 'epc', source: 'wordpress' },
    '/investments': { slug: 'investments', source: 'wordpress' },
    '/about-us': { slug: 'about-us', source: 'markdown' },
    '/company': { slug: 'company', source: 'wordpress' },
    '/carbon-emissions': { slug: 'carbon-emissions', source: 'wordpress' },
    '/mission': { slug: 'mission', source: 'wordpress' },
    '/terms-and-conditions': { slug: 'terms-and-conditions', source: 'wordpress' },
    '/privacy-policy': { slug: 'privacy-policy', source: 'wordpress' },
    '/affilate-activity-disclosure': { slug: 'affilate-activity-disclosure', source: 'wordpress' },
    '/club': { slug: 'club', source: 'wordpress' },
    '/energy': { slug: 'energy', source: 'markdown' },
    '/tesla': { slug: 'tesla', source: 'wordpress' },
    '/finance': { slug: 'finance', source: 'wordpress' },
    '/calculators': { slug: 'calculators', source: 'wordpress' },
    '/misc': { slug: 'misc', source: 'wordpress' },
    '/test-page': { slug: 'test-page', source: 'markdown' },
    '/renewables': { slug: 'renewables', source: 'markdown' },
    '/epc-checklist': { slug: 'epc-checklist', source: 'markdown' },
    '/contact-us': { slug: 'contact-us', source: 'markdown' },
    '/quicklinks': { slug: 'quicklinks', source: 'markdown' }
};